/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: skylajade69 (https://sketchfab.com/skylajade69)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ruin-helpi-85daccc4eafd4a5eaad7d628d8423144
Title: Ruin Helpi
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations, OrbitControls } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Doll(props) {
  const group = useRef()
//   useFrame((state,delta)=>{
//       state.mouse;
//       group.current.rotation.y+=delta*3;
//   })
  const ref=useRef()
    useFrame((state,delta)=>{
        if(!!ref.current){
            const {x,y}=state.mouse;
            ref.current.setAzimuthalAngle(-x*Math.PI/2);
            ref.current.setPolarAngle((y+0.4)*Math.PI)
        }
    },[ref.current])
  const { nodes, materials, animations } = useGLTF('/ruin_helpi.glb')
  const { actions } = useAnimations(animations, group)
  return (<>
    <OrbitControls enableRotate={true} ref={ref} minPolarAngle={[3.145/6]} maxPolarAngle={[3.145/1.4]}/>
    <group ref={group} {...props} dispose={null} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Helpi_pm_ARM_64">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Face}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Eyes}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.EyeShadow}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.Material}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials.Roupinha}
                    skeleton={nodes.Object_12.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.Hand}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials.BlueGlow}
                    skeleton={nodes.Object_14.skeleton}
                  />
                  <skinnedMesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials.BlueGlow}
                    skeleton={nodes.Object_16.skeleton}
                  />
                  <skinnedMesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials.Metal}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials.material}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    name="Object_20"
                    geometry={nodes.Object_20.geometry}
                    material={materials.EyeGlow}
                    skeleton={nodes.Object_20.skeleton}
                  />
                  <skinnedMesh
                    name="Object_22"
                    geometry={nodes.Object_22.geometry}
                    material={materials.material_10}
                    skeleton={nodes.Object_22.skeleton}
                  />
                  <skinnedMesh
                    name="Object_24"
                    geometry={nodes.Object_24.geometry}
                    material={materials.Face}
                    skeleton={nodes.Object_24.skeleton}
                  />
                  <skinnedMesh
                    name="Object_26"
                    geometry={nodes.Object_26.geometry}
                    material={materials.Face}
                    skeleton={nodes.Object_26.skeleton}
                  />
                  <skinnedMesh
                    name="Object_28"
                    geometry={nodes.Object_28.geometry}
                    material={materials.Face}
                    skeleton={nodes.Object_28.skeleton}
                  />
                  <skinnedMesh
                    name="Object_30"
                    geometry={nodes.Object_30.geometry}
                    material={materials.BlueGlow}
                    skeleton={nodes.Object_30.skeleton}
                  />
                  <skinnedMesh
                    name="Object_31"
                    geometry={nodes.Object_31.geometry}
                    material={materials.Metal}
                    skeleton={nodes.Object_31.skeleton}
                  />
                  <skinnedMesh
                    name="Object_32"
                    geometry={nodes.Object_32.geometry}
                    material={materials.VisorGlass}
                    skeleton={nodes.Object_32.skeleton}
                  />
                  <skinnedMesh
                    name="Object_33"
                    geometry={nodes.Object_33.geometry}
                    material={materials.OrangeLight}
                    skeleton={nodes.Object_33.skeleton}
                  />
                  <skinnedMesh
                    name="Object_34"
                    geometry={nodes.Object_34.geometry}
                    material={materials.VisorSymbol}
                    skeleton={nodes.Object_34.skeleton}
                  />
                  <group name="blank_55" />
                  <group name="Bodysmd_56" />
                  <group name="EarBudssmd_57" />
                  <group name="Eyesdmx_58" />
                  <group name="Hatsmd_59" />
                  <group name="Headdmx_60" />
                  <group name="Teethsmd_61" />
                  <group name="Tonguesmd_62" />
                  <group name="Visorsmd_63" />
                </group>
              </group>
              <group
                name="anim_attachment_RH_65"
                position={[-0.336, 0.435, -0.047]}
                rotation={[Math.PI / 2, 1.571, 0]}
                scale={0.019}
              />
              <group
                name="anim_attachment_LH_66"
                position={[0.335, 0.435, -0.048]}
                rotation={[Math.PI / 2, 1.571, 0]}
                scale={0.019}
              />
              <group
                name="anim_attachment_head_67"
                position={[-0.001, 0.547, -0.049]}
                rotation={[Math.PI / 2, 1.571, 0]}
                scale={0.019}
              />
              <group
                name="eyes_68"
                position={[-0.001, 0.595, 0.046]}
                rotation={[Math.PI / 2, 0, -1.398]}
                scale={0.019}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/ruin_helpi.glb')