/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Berk Gedik (https://sketchfab.com/berkgedik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cube-robot-animated-30a8e15725cf4feb9a3c8423f89d7df8
Title: Cube Robot - Animated
*/

import React, { useContext, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { AnimationStore } from '../Store/AnimationStore'

export default function Model(props) {
let roboScale=window.innerWidth<800?3:5.5
if(window.innerWidth<420){
    roboScale=1.5;
}
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/flingRobo.glb')
  const { actions,names } = useAnimations(animations, group)
  const {touch}=useContext(AnimationStore)
  useEffect(()=>{
    if(touch) actions[names[0]].play();
    else actions[names[0]].stop();
  },[touch])
  return (
    <group ref={group} {...props} dispose={null} scale={roboScale} position={[-0.3,1,0]}>
      <group name="Sketchfab_Scene">
        <group
          name="_rootJoint"
          position={[0, -0.074, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.2}>
          <group name="Bone_01" position={[0, 0, -0.242]} rotation={[-1.561, 0.018, 3.142]}>
            <group
              name="Bone001_02"
              position={[0, -0.769, 0]}
              rotation={[0, 0, Math.PI]}
              scale={[1, 1.27, 1]}>
              <group name="Bone001_end_028" position={[0, 0.74, 0]} />
              <group
                name="Cylinder013"
                position={[0, 0.09, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1, 1, 0.906]}>
                <mesh
                  name="Cylinder013_Material008_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder013_Material008_0.geometry}
                  material={materials['Material.008']}
                />
              </group>
            </group>
            <group name="Bone002_03" rotation={[0, 0, 0.931]}>
              <group name="Bone003_04" position={[0, 1.148, 0]} rotation={[0, 0, 0.662]}>
                <group name="Bone004_05" position={[0, 0.564, 0]} rotation={[0.038, 0.029, 1.029]}>
                  <group
                    name="Bone005_06"
                    position={[0, 0.855, 0]}
                    rotation={[0.023, 0.016, 0.943]}>
                    <group
                      name="Bone006_07"
                      position={[0, 1.63, 0]}
                      rotation={[0.011, 0.006, 0.602]}>
                      <group
                        name="Bone007_08"
                        position={[0, 0.53, 0]}
                        rotation={[-0.013, -0.002, -0.737]}>
                        <group name="Bone007_end_029" position={[0, 0.564, 0]} />
                        <group
                          name="Cube028"
                          position={[0.172, -4.432, 0.009]}
                          rotation={[-Math.PI / 2, 1.531, -Math.PI]}>
                          <mesh
                            name="Cube028_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube028_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                        <group
                          name="Cylinder040"
                          position={[0.172, -4.432, 0.009]}
                          rotation={[-Math.PI / 2, -0.039, -Math.PI / 2]}>
                          <mesh
                            name="Cylinder040_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder040_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                      </group>
                      <group
                        name="Cylinder030"
                        position={[-2.123, -3.365, 0.009]}
                        rotation={[-Math.PI / 2, 0.498, -Math.PI / 2]}>
                        <mesh
                          name="Cylinder030_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cylinder030_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                      <group
                        name="Cube026"
                        position={[-2.123, -3.365, 0.009]}
                        rotation={[Math.PI / 2, 1.072, 0]}>
                        <mesh
                          name="Cube026_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube026_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                    </group>
                    <group
                      name="Bone008_09"
                      position={[0, 1.63, 0]}
                      rotation={[0.501, -0.113, -0.199]}>
                      <group
                        name="Bone009_010"
                        position={[0, 0.53, 0]}
                        rotation={[-0.504, 0.009, 0.545]}>
                        <group name="Bone009_end_030" position={[0, 0.635, 0]} />
                        <group
                          name="Cube027"
                          position={[-1.342, -4.232, -0.251]}
                          rotation={[1.571, 1.335, 0]}>
                          <mesh
                            name="Cube027_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube027_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                        <group
                          name="Cylinder039"
                          position={[-1.342, -4.232, -0.251]}
                          rotation={[-1.57, 0.236, -Math.PI / 2]}>
                          <mesh
                            name="Cylinder039_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder039_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                      </group>
                      <group
                        name="Cylinder038"
                        position={[0.268, -3.46, 1.944]}
                        rotation={[-2.08, -0.132, -Math.PI / 2]}>
                        <mesh
                          name="Cylinder038_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cylinder038_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                      <group
                        name="Cube025"
                        position={[0.268, -3.46, 1.944]}
                        rotation={[-2.08, 1.439, -Math.PI]}>
                        <mesh
                          name="Cube025_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube025_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                    </group>
                    <group
                      name="Bone010_011"
                      position={[0, 1.63, 0]}
                      rotation={[-0.499, 0.065, -0.118]}>
                      <group
                        name="Bone011_012"
                        position={[0, 0.506, 0]}
                        rotation={[0.52, 0.012, 0.512]}>
                        <group name="Bone011_end_031" position={[0, 0.63, 0]} />
                        <group
                          name="Cube019"
                          position={[-1.223, -4.245, 0.277]}
                          rotation={[1.566, 1.359, 0]}>
                          <mesh
                            name="Cube019_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube019_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                        <group
                          name="Cylinder031"
                          position={[-1.223, -4.245, 0.277]}
                          rotation={[-1.576, 0.211, -Math.PI / 2]}>
                          <mesh
                            name="Cylinder031_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder031_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                      </group>
                      <group
                        name="Cube018"
                        position={[0.188, -3.475, -1.927]}
                        rotation={[-1.062, 1.459, -Math.PI]}>
                        <mesh
                          name="Cube018_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube018_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                      <group
                        name="Cylinder037"
                        position={[0.188, -3.475, -1.927]}
                        rotation={[-1.062, -0.112, -Math.PI / 2]}>
                        <mesh
                          name="Cylinder037_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cylinder037_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                    </group>
                    <group
                      name="Bone013_013"
                      position={[-0.326, 0.587, 0.003]}
                      rotation={[-0.052, -0.005, 0.082]}>
                      <group name="Bone013_end_00" position={[0, 1.011, 0]} />
                      <group
                        name="BezierCurve003"
                        position={[-0.411, -2.895, -0.039]}
                        rotation={[-3.084, 0, -1.466]}>
                        <mesh
                          name="BezierCurve003_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.BezierCurve003_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                    </group>
                    <group
                      name="Cylinder027"
                      position={[-0.347, -2.333, -0.013]}
                      rotation={[1.577, 1.548, 0]}>
                      <mesh
                        name="Cylinder027_Material008_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder027_Material008_0.geometry}
                        material={materials['Material.008']}
                      />
                    </group>
                    <group
                      name="Cube016"
                      position={[-0.347, -2.333, -0.013]}
                      rotation={[1.577, 1.548, 0]}>
                      <mesh
                        name="Cube016_Material008_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube016_Material008_0.geometry}
                        material={materials['Material.008']}
                      />
                    </group>
                    <group
                      name="Cube020"
                      position={[-0.347, -2.333, -0.013]}
                      rotation={[1.577, 1.548, 0]}>
                      <mesh
                        name="Cube020_Material008_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube020_Material008_0.geometry}
                        material={materials['Material.008']}
                      />
                    </group>
                  </group>
                  <group
                    name="Sphere006"
                    position={[-0.318, -1.482, 0]}
                    rotation={[1.571, 1.56, 0]}>
                    <mesh
                      name="Sphere006_Material008_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere006_Material008_0.geometry}
                      material={materials['Material.008']}
                    />
                  </group>
                  <group
                    name="Cylinder026"
                    position={[-0.318, -1.482, 0]}
                    rotation={[1.571, 1.56, 0]}>
                    <mesh
                      name="Cylinder026_Material008_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder026_Material008_0.geometry}
                      material={materials['Material.008']}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder025"
                  position={[-0.336, -0.914, 0]}
                  rotation={[Math.PI / 2, 1.548, 0]}>
                  <mesh
                    name="Cylinder025_Material008_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder025_Material008_0.geometry}
                    material={materials['Material.008']}
                  />
                </group>
                <group
                  name="Sphere007"
                  position={[-0.336, -0.914, 0]}
                  rotation={[Math.PI / 2, 1.548, 0]}>
                  <mesh
                    name="Sphere007_Material008_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere007_Material008_0.geometry}
                    material={materials['Material.008']}
                  />
                </group>
              </group>
            </group>
            <group name="Bone014_014" rotation={[0, 0, -0.931]}>
              <group name="Bone015_015" position={[0, 1.148, 0]} rotation={[0, 0, -0.662]}>
                <group
                  name="Bone016_016"
                  position={[0, 0.564, 0]}
                  rotation={[0.02, -0.019, -1.078]}>
                  <group
                    name="Bone017_017"
                    position={[0, 0.855, 0]}
                    rotation={[0.007, -0.007, -0.87]}>
                    <group
                      name="Bone018_018"
                      position={[0, 1.63, 0]}
                      rotation={[0.009, -0.003, -0.546]}>
                      <group
                        name="Bone019_019"
                        position={[0, 0.53, 0]}
                        rotation={[-0.026, 0.001, 0.942]}>
                        <group name="Bone019_end_032" position={[0, 0.564, 0]} />
                        <group
                          name="Cylinder029"
                          position={[-0.172, -4.432, 0.009]}
                          rotation={[Math.PI / 2, -0.039, -Math.PI / 2]}>
                          <mesh
                            name="Cylinder029_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder029_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                        <group
                          name="Cube024"
                          position={[-0.172, -4.432, 0.009]}
                          rotation={[1.571, 1.531, 3.141]}>
                          <mesh
                            name="Cube024_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube024_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                      </group>
                      <group
                        name="Cube011"
                        position={[2.123, -3.365, 0.009]}
                        rotation={[-1.571, 1.072, 0]}>
                        <mesh
                          name="Cube011_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube011_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                      <group
                        name="Cylinder032"
                        position={[2.123, -3.365, 0.009]}
                        rotation={[Math.PI / 2, 0.498, -Math.PI / 2]}>
                        <mesh
                          name="Cylinder032_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cylinder032_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                    </group>
                    <group
                      name="Bone020_020"
                      position={[0, 1.63, 0]}
                      rotation={[0.45, 0.236, 0.42]}>
                      <group
                        name="Bone021_021"
                        position={[0, 0.53, 0]}
                        rotation={[-0.496, -0.028, -0.864]}>
                        <group name="Bone021_end_033" position={[0, 0.635, 0]} />
                        <group
                          name="Cube023"
                          position={[1.342, -4.232, -0.251]}
                          rotation={[-1.57, 1.335, 0]}>
                          <mesh
                            name="Cube023_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube023_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                        <group
                          name="Cylinder036"
                          position={[1.342, -4.232, -0.251]}
                          rotation={[1.571, 0.236, -Math.PI / 2]}>
                          <mesh
                            name="Cylinder036_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder036_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                      </group>
                      <group
                        name="Cylinder033"
                        position={[-0.268, -3.46, 1.944]}
                        rotation={[1.061, -0.132, -Math.PI / 2]}>
                        <mesh
                          name="Cylinder033_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cylinder033_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                      <group
                        name="Cube021"
                        position={[-0.268, -3.46, 1.944]}
                        rotation={[1.061, 1.439, 3.142]}>
                        <mesh
                          name="Cube021_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube021_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                    </group>
                    <group
                      name="Bone022_022"
                      position={[0, 1.63, 0]}
                      rotation={[-0.486, -0.166, 0.323]}>
                      <group
                        name="Bone023_023"
                        position={[0, 0.506, 0]}
                        rotation={[0.522, -0.017, -0.59]}>
                        <group name="Bone023_end_034" position={[0, 0.63, 0]} />
                        <group
                          name="Cube012"
                          position={[1.223, -4.245, 0.277]}
                          rotation={[-1.576, 1.359, 0]}>
                          <mesh
                            name="Cube012_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube012_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                        <group
                          name="Cylinder035"
                          position={[1.223, -4.245, 0.277]}
                          rotation={[1.566, 0.211, -Math.PI / 2]}>
                          <mesh
                            name="Cylinder035_Material008_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder035_Material008_0.geometry}
                            material={materials['Material.008']}
                          />
                        </group>
                      </group>
                      <group
                        name="Cylinder034"
                        position={[-0.188, -3.475, -1.927]}
                        rotation={[2.079, -0.112, -Math.PI / 2]}>
                        <mesh
                          name="Cylinder034_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cylinder034_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                      <group
                        name="Cube022"
                        position={[-0.188, -3.475, -1.927]}
                        rotation={[2.08, 1.459, 3.142]}>
                        <mesh
                          name="Cube022_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube022_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                    </group>
                    <group
                      name="Bone025_024"
                      position={[0.326, 0.587, 0.003]}
                      rotation={[-0.052, 0.005, -0.082]}>
                      <group name="Bone025_end_035" position={[0, 1.011, 0]} />
                      <group
                        name="BezierCurve001"
                        position={[0.411, -2.895, -0.039]}
                        rotation={[0.058, 0, -1.466]}>
                        <mesh
                          name="BezierCurve001_Material008_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.BezierCurve001_Material008_0.geometry}
                          material={materials['Material.008']}
                        />
                      </group>
                    </group>
                    <group
                      name="Cylinder019"
                      position={[0.347, -2.333, -0.013]}
                      rotation={[-1.565, 1.548, 0]}>
                      <mesh
                        name="Cylinder019_Material008_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder019_Material008_0.geometry}
                        material={materials['Material.008']}
                      />
                    </group>
                    <group
                      name="Cube009"
                      position={[0.347, -2.333, -0.013]}
                      rotation={[-1.565, 1.548, 0]}>
                      <mesh
                        name="Cube009_Material008_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube009_Material008_0.geometry}
                        material={materials['Material.008']}
                      />
                    </group>
                    <group
                      name="Cube017"
                      position={[0.347, -2.333, -0.013]}
                      rotation={[-1.565, 1.548, 0]}>
                      <mesh
                        name="Cube017_Material008_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube017_Material008_0.geometry}
                        material={materials['Material.008']}
                      />
                    </group>
                  </group>
                  <group
                    name="Sphere003"
                    position={[0.318, -1.482, 0]}
                    rotation={[-1.571, 1.56, 0]}>
                    <mesh
                      name="Sphere003_Material008_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere003_Material008_0.geometry}
                      material={materials['Material.008']}
                    />
                  </group>
                  <group
                    name="Cylinder018"
                    position={[0.318, -1.482, 0]}
                    rotation={[-1.571, 1.56, 0]}>
                    <mesh
                      name="Cylinder018_Material008_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder018_Material008_0.geometry}
                      material={materials['Material.008']}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder017"
                  position={[0.336, -0.914, 0]}
                  rotation={[-1.571, 1.548, 0]}>
                  <mesh
                    name="Cylinder017_Material008_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder017_Material008_0.geometry}
                    material={materials['Material.008']}
                  />
                </group>
                <group name="Sphere004" position={[0.336, -0.914, 0]} rotation={[-1.571, 1.548, 0]}>
                  <mesh
                    name="Sphere004_Material008_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere004_Material008_0.geometry}
                    material={materials['Material.008']}
                  />
                </group>
              </group>
            </group>
            <group
              name="Bone026_025"
              position={[0, -1.299, 0]}
              rotation={[0, 0, Math.PI]}
              scale={[1, 1.181, 1]}>
              <group name="Bone026_end_036" position={[0, 0.74, 0]} />
              <group
                name="Cylinder015"
                position={[0, -0.383, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1, 1, 0.899]}>
                <mesh
                  name="Cylinder015_Material008_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder015_Material008_0.geometry}
                  material={materials['Material.008']}
                />
              </group>
            </group>
            <group name="Cube008" position={[0, 0.37, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
              <mesh
                name="Cube008_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube008_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group
              name="Cylinder011"
              position={[0, -0.628, 0]}
              rotation={[-Math.PI / 2, 0, Math.PI]}>
              <mesh
                name="Cylinder011_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder011_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group name="Cylinder014" position={[0, 0.669, -0.001]} rotation={[0, -1.571, 0]}>
              <mesh
                name="Cylinder014_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder014_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group
              name="Cylinder020"
              position={[-0.401, 0.722, -0.973]}
              rotation={[0, 0, -Math.PI / 2]}>
              <mesh
                name="Cylinder020_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder020_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group name="Cube013" position={[0, 0.37, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
              <mesh
                name="Cube013_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube013_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group
              name="Sphere005"
              position={[-0.402, 0.721, -1.07]}
              rotation={[Math.PI, 0, Math.PI]}>
              <mesh
                name="Sphere005_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere005_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group name="Cube014" position={[0, 0.393, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
              <mesh
                name="Cube014_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube014_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group name="Plane001" position={[0, 0.707, 1.007]} rotation={[Math.PI, 0, Math.PI]}>
              <mesh
                name="Plane001_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Plane001_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group name="Cube015" position={[0, -0.053, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
              <mesh
                name="Cube015_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube015_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group
              name="Cylinder023"
              position={[0.979, -0.14, 0.436]}
              rotation={[-1.797, -1.558, -1.795]}>
              <mesh
                name="Cylinder023_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder023_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group name="Cylinder024" position={[0, 0.37, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
              <mesh
                name="Cylinder024_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder024_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
            <group name="Cylinder016" position={[0, 0.37, 0]} rotation={[Math.PI / 2, 0, -Math.PI]}>
              <mesh
                name="Cylinder016_Material008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder016_Material008_0.geometry}
                material={materials['Material.008']}
              />
            </group>
          </group>
          <group name="Bone012_026" position={[1.237, 0.093, -1.793]}>
            <group name="Bone012_end_037" position={[0, 0.989, 0]} />
          </group>
          <group name="Bone024_027" position={[-1.237, 0.093, -1.831]}>
            <group name="Bone024_end_038" position={[0, 0.989, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/flingRobo.glb')
