/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AJ (https://sketchfab.com/ArneJans)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lone-graverobber-in-a-graveyard-db3174a516b241a0afe0b13798ac59ec
Title: Lone graverobber in a graveyard
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const group = useRef()
  useFrame((state,delta)=>{
    group.current.position.y=Math.sin(state.clock.elapsedTime);
    group.current.position.x=Math.sin(state.clock.elapsedTime);
    group.current.rotation.y+=delta*0.2;
  })
  const { nodes, materials, animations } = useGLTF('/lone_graverobber_in_a_graveyard.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="bbf1860f093f4700a008af726bdeb46efbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Retopo_LP001"
                  position={[-155.714, 267.267, 104.598]}
                  rotation={[0, -Math.PI / 4, 0]}
                  scale={10.766}
                />
                <group
                  name="Character"
                  position={[-145.328, 46.275, 101.446]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
                  scale={58.7}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.CharacterMaterial}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <group
                      name="Object_8"
                      position={[-155.714, 267.267, 104.598]}
                      rotation={[0, -Math.PI / 4, 0]}
                      scale={10.766}
                    />
                  </group>
                </group>
                <group
                  name="Empty"
                  position={[-227.537, 291.477, 218.619]}
                  rotation={[0.108, -0.578, -2.308]}
                  scale={100}>
                  <group
                    name="Retopo_LP002"
                    position={[1.179, 0.069, -0.9]}
                    rotation={[1.701, -0.859, 3.03]}>
                    <mesh
                      name="Retopo_LP002_CharacterMaterial001_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Retopo_LP002_CharacterMaterial001_0.geometry}
                      material={materials['CharacterMaterial.001']}
                    />
                  </group>
                </group>
                <group
                  name="lpground002"
                  position={[36.778, -302.051, -393.896]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[1235.528, 1063.916, 1235.528]}>
                  <group name="Graves001">
                    <mesh
                      name="Graves001_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Graves001_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground233">
                    <mesh
                      name="lpground233_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground233_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground244">
                    <mesh
                      name="lpground244_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground244_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground245">
                    <mesh
                      name="lpground245_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground245_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground246">
                    <mesh
                      name="lpground246_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground246_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground248">
                    <mesh
                      name="lpground248_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground248_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground249">
                    <mesh
                      name="lpground249_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground249_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground250">
                    <mesh
                      name="lpground250_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground250_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground251">
                    <mesh
                      name="lpground251_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground251_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground253">
                    <mesh
                      name="lpground253_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground253_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground254">
                    <mesh
                      name="lpground254_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground254_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground255">
                    <mesh
                      name="lpground255_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground255_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground256">
                    <mesh
                      name="lpground256_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground256_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground259">
                    <mesh
                      name="lpground259_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground259_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground260">
                    <mesh
                      name="lpground260_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground260_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground261">
                    <mesh
                      name="lpground261_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground261_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                  <group name="lpground262">
                    <mesh
                      name="lpground262_EnviromentMaterial_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.lpground262_EnviromentMaterial_0.geometry}
                      material={materials.EnviromentMaterial}
                    />
                  </group>
                </group>
                <group
                  name="LAMP"
                  position={[-247.833, 111.211, 337.024]}
                  rotation={[0, 1.54, 0]}
                  scale={100}>
                  <group name="Object_145" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_146" />
                  </group>
                </group>
                <group
                  name="MOON"
                  position={[-712.114, 1419.47, -2187.636]}
                  rotation={[-1.312, 1.187, 0.997]}
                  scale={100}>
                  <group name="Object_148" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_149" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lone_graverobber_in_a_graveyard.glb')
