/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: silicat (https://sketchfab.com/silicat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hoefnagel-creature-9a92596a121f412299dfbc61b1bb01aa
Title: Hoefnagel creature
*/

import React, { useRef } from 'react'
import { Html, OrbitControls, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
    const group=useRef();
    const ref=useRef();
    useFrame((state,delta)=>{
      group.current.position.y=(Math.sin(state.clock.elapsedTime)-2);
        if(!!ref.current){
            const {x,y}=state.mouse;
            ref.current.setAzimuthalAngle(-x*Math.PI/4);
            // ref.current.setPolarAngle((y+0.4)*Math.PI)
        }
    })
  const { nodes, materials } = useGLTF('/hoefnagel_creature.glb')
  return (
    <>
    <OrbitControls enableZoom={false} enableRotate={false} ref={ref}/>
    <group {...props} dispose={null} ref={group}>
    <Html className='text-white text-5xl font-extrabold stylish-regular shadow' position={[-0.2,0.8,0.3]}>NITHIN'S</Html>
    <Html className='text-red-600 text-8xl font-extrabold stylish-regular ' position={[0.2,0.4,1]}>Creative</Html>
    <Html className='text-white text-7xl font-extrabold stylish-regular -z-50' position={[-0.2,-0,-1]}>Portfolio</Html>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Golden_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Skull_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Wings_Material}
        position={[0.078, 0, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
    </group>
    </>
  )
}

useGLTF.preload('/hoefnagel_creature.glb')
